INSERT INTO tweet (id_parent, id_user, text)
VALUES
(1, 0, 'This is my first twitter! Yeah!'),
(1, 0, 'Hello Twitter'),
(1, 0, 'Today is a great day!'),
(1, 0, 'Cant wait til summer!!!'),
(1, 0, 'Im bored!'),
(1, 0, 'Whats 2+2?'),
(1, 0, 'Im like to eat kebab'),
(1, 0, 'Programming in spring boot is fun'),
(1, 0, 'hehehehe, im drunk'),
(1, 0, 'Donald Trump for prezzz'),

(2, 0, 'Going to Japan this easter! Konnichiwa!'),
(2, 0, 'Tokyo is amazing!!'),
(2, 0, 'Kyoto is a cool city!'),
(2, 0, 'Cant wait til summer!!!'),
(2, 0, 'Im bored!'),
(2, 0, 'This is my first twitter! Yeah!'),
(2, 0, 'Hello Twitter'),
(2, 0, 'Today is a great day!'),
(2, 0, 'Cant wait til summer!!!'),
(2, 0, 'aloe vera is good for tha skin'),

(3, 0, '#Bærum Politiet har kommet over russebuss som tidligere har fått en advarsel vedr. støy. Den støyet fortsatt og vi har tatt en vital del av musikkanlegget.'),
(3, 0, 'Vi har fått personen ned fra taket i god behold.'),
(3, 0, 'How about you watch your ugly lookin mouth when you talk to the two time.'),
(3, 0, 'Now that firestorm has duos and can replace fortnite. Let''s do a duo triple threat challenge like we talked about. DMs for the date and time.'),
(3, 0, 'Watch Litecoin surviving the test of time. It''s not easy fighting off all the shitcoins and scamcoins to stay in the top 10. '),
(3, 0, 'OKEx will support the airdrops for USDT-TRC20 holders. You can convert your USDT to USDT-TRC20 in your Assets Account to receive the bonus.'),
(3, 0, 'My kids enjoying watching the 2x while I make them a filet mignon dinner. @drdisrespect They are learning how to hit that 360 shot and how to be on top of that mountain, but only half way up.'),
(3, 0, '#Consensus2019 discount codes are bigger than actual ticket prices for @magicalcrypto conference'),
(3, 0, 'I have to say this newly launched live SLOTS game is crazy! '),
(3, 0, 'aloe vera is good for tha skin'),

(4, 0, 'Violence. SPEED. Momentum.” - Heading into Game 1 '),
(4, 0, 'Festen er avsluttet og det ble gitt pålegg om å holde ro.'),
(4, 0, 'mmmmmRecapitashe?!?!?! LIVE ETA 30ish Mins!'),
(4, 0, 'Air-drop for voters , 2000 TONE will be airdrop for voters this week ! Cheers ! Celebrate for TRON-ONE CONTENT PROTOCAL !'),
(4, 0, 'We have recorded the highest transaction volume and transaction within 24hours from launch! :)'),
(4, 0, 'Guests get a random one in their swag bags. VIPs get a set of 4 with matching serial numbers! 😮'),
(4, 0, 'Thanks for the support to #TRC20 based #USDT from VenaPi. #TRON #TRX $USDT'),
(4, 0, 'It''s a 150 billion dollar industry.  Where are the quality competitive shooter games?'),
(4, 0, 'This will be the Mans who Bodies The Night King'),
(4, 0, 'En person letter skadd som kjøres til legevakten av ambulanse. Politiet oppretter sak på forholdet.');
